// import Head from "next/head";
// import signin from "./signin";



// export default function Home() {
//   return (
//     <div>
//       <Head>
//         <title>index page</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//         <link
//           href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
//           rel="stylesheet"
//         />
        
//       </Head>
//       <body>
//          <p>indexpages</p>
//         <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
//       </body>
//     </div>
//   );
// }

 
import Link from 'next/link';
import Banner from '../components/Banner';
import Services from '../components/Services';

const Index = () => {
  return (
    <div>
        <div>
            <Banner/>
           
           <div>
               <Services/>
           </div>
        </div>
        <h1>footer</h1>
    </div>
);
            
        
   
};

export default Index;
